# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('seating_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Customer')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Space')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_api.Payment')),
                ('card_type', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_api.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_api.Payment')),
                ('check_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Payment'),
        ),
        migrations.AddField(
            model_name='seating',
            name='ticket_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Ticket'),
        ),
        migrations.AddField(
            model_name='position',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Staff'),
        ),
    ]
